# Generated by Django 5.1.6 on 2025-02-28 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_caso', models.IntegerField(null=True)),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('f_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('sospechosos', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('nombre_caso', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30, null=True)),
                ('departamento', models.CharField(max_length=30, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('perito', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'casos',
            },
        ),
        migrations.CreateModel(
            name='Huellas',
            fields=[
                ('id_huella', models.AutoField(primary_key=True, serialize=False)),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('caso', models.IntegerField(null=True)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='original/')),
                ('procesada_image', models.ImageField(blank=True, null=True, upload_to='procesada/')),
                ('minutiae_image', models.ImageField(blank=True, null=True, upload_to='minucias/')),
                ('minutiae_csv', models.FileField(blank=True, null=True, upload_to='datos/')),
                ('activate', models.BooleanField(default=True)),
                ('persona', models.IntegerField(null=True)),
                ('tipo', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'huellas',
            },
        ),
        migrations.CreateModel(
            name='Implicado',
            fields=[
                ('id_implicado', models.AutoField(primary_key=True, serialize=False)),
                ('caso', models.IntegerField(null=True)),
                ('nombres', models.CharField(default='', max_length=50)),
                ('apellido_paterno', models.CharField(default='', max_length=50)),
                ('apellido_materno', models.CharField(default='', max_length=50)),
                ('carnet_identidad', models.CharField(default='', max_length=20, unique=True)),
                ('expedido_en', models.CharField(default='', max_length=30)),
                ('fecha_nacimiento', models.DateField(auto_now_add=True, null=True)),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('lugar_nacimiento', models.CharField(default='', max_length=100)),
                ('direccion', models.CharField(default='', max_length=100)),
                ('nacionalidad', models.CharField(default='', max_length=30)),
                ('ocupacion', models.CharField(default='', max_length=50)),
                ('color_pelo', models.CharField(default='', max_length=30)),
                ('color_piel', models.CharField(default='', max_length=30)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('altura_m', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('sexo', models.CharField(default='', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'implicados',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('ci', models.IntegerField()),
                ('f_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('cede', models.CharField(max_length=30, null=True)),
                ('cargo', models.CharField(max_length=30, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
    ]
